# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('coupon_type', models.CharField(choices=[('percentage', 'percentage'), ('fixed_amount', 'fixed'), ('shipping', 'shipping')], default='percentage', max_length=40)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
